<?php
return array(
    'test'=>array(
        'type'=>'class',
        'class'=>'ApiTest',
    ),
    'roll'=>array(
        'type'=>'model',
        'model'=>'Roll',
        'GET'=>array(
            'fields'=>array(
                'id',
                'name',
            ),
        ),
    ),
    'user'=>array(
        'type'=>'model',
        'model'=>'User',
        'GET'=>array(
            'fields'=>array(
                'id',
                'name',
                'email',
                'roll_id',
            ),
        ),
    ),
    'useradmin'=>array(
        'roll'=>'admin',
        'type'=>'model',
        'model'=>'User',
        'POST'=>array(
            'fields'=>array(
                'name',
                'email',
                'roll_id',
                'enabled',
            )
        )
    ),
);
