<?php
return array(
    'test'=>array(
        'roll'=>array('test'),
        'type'=>'class',
        'class'=>'ApiTest',
    ),
    'roll'=>array(
        'type'=>'model',
        'model'=>'Roll',
        'GET'=>array(
            'fields'=>array(
                'id',
                'name',
            ),
        ),
    ),
    'user'=>array(
        'type'=>'model',
        'model'=>'User',
        'GET'=>array(
            'fields'=>array(
                'id',
                'name',
                'email',
                'roll_id',
                'valid',
            ),
        ),
        'POST'=>array(
            'roll'=>array(
                'admin',
            ),
            'fields'=>array(
                'name',
                'email',
                'roll_id',
                'valid',
            )
        ),
        'PUT'=>array(
            'roll'=>array(
                'admin',
            ),
            'fields'=>array(
                'pass',
                'valid',
            )
        )
    ),
);
